exp_name : no_amp_test2

random_seed: 20

model:
  type: torchvision
  name: fcn_resnet50
  pretrained: True

train_img: '/data/ephemeral/home/data/train/DCM'
train_label: '/data/ephemeral/home/data/train/outputs_json'
test_img: /data/ephemeral/home/data/test/DCM
pt_saved_dir: '/data/ephemeral/home/lsh/result'
pt_loaded_dir: '/data/ephemeral/home/lsh/result/basetest/fcn_resnet50.pt'

transform:
  transform_type: albumentations
  augmentations:
    - type: Resize
      params:
        height: 512
        width: 512

train_batch: 4
val_batch: 8
num_epochs: 150
val_every: 5
lr: 0.0001

criterion: BCEWithLogitsLoss
optimizer: Adam