# Project Settings
proj_name: "baseline"
exp_name: "basetest"

# General Settings
random_seed: 20
debug: false

# Model Configuration
model:
  type: "torchvision"
  name: "fcn_resnet50"
  pretrained: true

# Optimizer & Scheduler Configuration
optimizer:
  type: "Adam"
  lr: 0.0001

criterion: "BCEWithLogitsLoss"

lr_scheduler:
  type: "CosineAnnealingLR"        # Learning rate scheduler
  params:
    T_max: 1                       # Maximum number of iterations
    eta_min: 0.00001               # Minimum learning rate

# Dataset Paths
paths:
  train_img: "/data/ephemeral/home/data/train/DCM"
  train_label: "/data/ephemeral/home/data/train/outputs_json"
  test_img: "/data/ephemeral/home/data/test/DCM"
  pt_saved_dir: "/data/ephemeral/home/level2-cv-semanticsegmentation-cv-20-lv3/checkpoints"
  pt_loaded_dir: "/data/ephemeral/home/level2-cv-semanticsegmentation-cv-20-lv3/checkpoints/fcn_resnet50.pt"

# Data Augmentation
transform:
  type: "albumentations"
  augmentations:
    - type: "Resize"
      params:
        height: 256
        width: 256

# Training Configuration
training:
  batch_size:
    train: 16
    val: 4
  num_epochs: 2
  validate_every: 1