# Project Settings
proj_name: "baseline"
exp_name: "basetest_1024_1024_30 epoch" # 실험 결과 저장

# General Settings
random_seed: 20
debug: true

# Model Configuration
model:
  type: "torchvision"
  name: "fcn_resnet50"
  pretrained: true


# Optimizer & Scheduler Configuration
optimizer:
  type: "Adam"
  lr: 0.0001

criterion: "BCEWithLogitsLoss"

# lr_scheduler:
#   type: 'ReduceLROnPlateau'  # 'CosineAnnealingLR', 'StepLR', 'ReduceLROnPlateau' 등
#   params:
#     factor: 0.1
#     patience: 5
#     mode: 'min'

# lr_scheduler:
#   type: "CosineAnnealingLR"         # 스케줄러 종류 (예: CosineAnnealingLR)
#   params:                           # 스케줄러에 필요한 파라미터들
#     T_max: 10                       # CosineAnnealingLR에 필요한 파라미터
#     eta_min: 0.0001                      # 최소 학습률

# Pseudo-Labeling Configuration
pseudo_labeling:
  enabled: false               # Pseudo-labeling 사용 여부
  confidence_threshold: 0.9   # Pseudo-labeling에 사용할 최소 신뢰도
  # max_pseudo_samples: 1000    # 사용할 최대 pseudo-label 샘플 수 (현재 구현 못함)
  pseudo_dir: "/data/ephemeral/home/level2-cv-semanticsegmentation-cv-20-lv3/data/test/outputs_json"  # Pseudo-label 파일 저장 경로

# Dataset Paths
paths:
  data: "/data/ephemeral/home/level2-cv-semanticsegmentation-cv-20-lv3/data/"
  train:
    image: "/data/ephemeral/home/level2-cv-semanticsegmentation-cv-20-lv3/data/train/DCM"
    label: "/data/ephemeral/home/level2-cv-semanticsegmentation-cv-20-lv3/data/train/outputs_json"
  test:
    image: "/data/ephemeral/home/level2-cv-semanticsegmentation-cv-20-lv3/data/test/DCM"
  model:
    save_dir: "/data/ephemeral/home/level2-cv-semanticsegmentation-cv-20-lv3/result"
    pt_loaded_dir: "/data/ephemeral/home/level2-cv-semanticsegmentation-cv-20-lv3/result/basetest/fcn_resnet50.pt"

# Data Augmentation
transform:
  type: albumentations
  augmentations:
    - type: Resize
      params:
        height: 1024
        width: 1024

# Training Configuration
training:
  batch_size:
    train: 1
    val: 1
  num_epochs: 30
  validate_every: 1