# test 파일 이미지 경로
image_root: /data/ephemeral/home/data/test/DCM


root_path: /data/ephemeral/home/ohs/level2-cv-semanticsegmentation-cv-12-lv3

CLASSES: [
    'finger-1', 'finger-2', 'finger-3', 'finger-4', 'finger-5',
    'finger-6', 'finger-7', 'finger-8', 'finger-9', 'finger-10',
    'finger-11', 'finger-12', 'finger-13', 'finger-14', 'finger-15',
    'finger-16', 'finger-17', 'finger-18', 'finger-19', 'Trapezium',
    'Trapezoid', 'Capitate', 'Hamate', 'Scaphoid', 'Lunate',
    'Triquetrum', 'Pisiform', 'Radius', 'Ulna',
]

batch_size: 2
num_workers: 2

threshold: 0.2

model_paths:
  256: []
  # 512: []
  512: 
    - /data/ephemeral/home/clear/level2-cv-semanticsegmentation-cv-20-lv3/ensemble/pan.pt
  1024:
    - /data/ephemeral/home/clear/level2-cv-semanticsegmentation-cv-20-lv3/ensemble/fcn_resnet50_1024_1024_30.pt
  2048: []

save_dir: ./soft_ensemble
output_name: output.csv