# test 파일 이미지 경로
image_root: /data/ephemeral/home/data/test/DCM


root_path: /data/ephemeral/home/ohs/level2-cv-semanticsegmentation-cv-12-lv3

CLASSES: [
    'finger-1', 'finger-2', 'finger-3', 'finger-4', 'finger-5',
    'finger-6', 'finger-7', 'finger-8', 'finger-9', 'finger-10',
    'finger-11', 'finger-12', 'finger-13', 'finger-14', 'finger-15',
    'finger-16', 'finger-17', 'finger-18', 'finger-19', 'Trapezium',
    'Trapezoid', 'Capitate', 'Hamate', 'Scaphoid', 'Lunate',
    'Triquetrum', 'Pisiform', 'Radius', 'Ulna',
]

batch_size: 2
num_workers: 2

threshold: 0.2

model_paths:
  hugging_face: []
  non:
    256:
      - /data/ephemeral/home/level2-cv-semanticsegmentation-cv-20-lv3/result/Ensemble/deeplabv3plus_resnet50.pt
    # 512: []
    512: 
      - /data/ephemeral/home/level2-cv-semanticsegmentation-cv-20-lv3/result/Ensemble/deeplabv3plus_regnetx_320.pt
      - /data/ephemeral/home/level2-cv-semanticsegmentation-cv-20-lv3/result/Ensemble/deeplabv3plus_resnet50.pt
      - /data/ephemeral/home/level2-cv-semanticsegmentation-cv-20-lv3/result/Ensemble/deeplabv3plus_resnet101.pt
      - /data/ephemeral/home/level2-cv-semanticsegmentation-cv-20-lv3/result/Ensemble/deeplabv3plus_resnext101_32x8d.pt
      - /data/ephemeral/home/level2-cv-semanticsegmentation-cv-20-lv3/result/Ensemble/deeplabv3plus_tf_efficientnet_cc_b1_8e.pt
      - /data/ephemeral/home/level2-cv-semanticsegmentation-cv-20-lv3/result/Ensemble/deeplabv3plus_xception71.pt
    1024: []
    2048: []

save_dir: /data/ephemeral/home/level2-cv-semanticsegmentation-cv-20-lv3/result/Ensemble/result
output_name: deeplabv3.csv